name: tiled

# micromamba create -n tiled -f environment.yml -y
# micromamba activate tiled

channels:
  - conda-forge
  - defaults

dependencies:
  - python >=3.8, <3.11
  - bson
  - event-model
  - pymongo
  - h5py
  - hdf5plugin
  - punx
  - pip
  - spec2nexus

  - pip:
    - databroker >=2.0.0b12
    - tiled[all] >=0.1.0a80
    - https://raw.githubusercontent.com/EPICS-synApps/support/master/utils/mdaPythonUtils/mdalib-2022.post9-py2.py3-none-any.whl
